title: Vítor Gabriel Reis Caitité
logo: /assets/img/eu.jpg
email: vitorcaitite@gmail.com
description: Welcome to my personal page :)
remote_theme: BDHU/minimalist
plugins:
  - jekyll-remote-theme
sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vcaitite
